### ISSUE TITLE
Brak źródła mapy

### ISSUE THREAD

**Issue by kasztan2** [ChrisRPL/ForestGarbageMapper#1]
Cześć, używasz mapy OpenStreetMap w projekcie, fajnie by było gdyby pojawiła się informacja o źródle mapy. OSM jest publikowany na licencji wymagającej podania źródła. [Więcej tutaj](https://www.openstreetmap.org/copyright). Nawet w [dokumentacji `flutter_map`](https://docs.fleaflet.dev/)  jest jakiś AttributionWidget.
Poza tym może warto dać link do repo na stronie projektu?

**Comment by SolveItProject** [comment]
Jasne, dodam info do readme i link do repo w zakladce about na stronie

**Comment by ChrisRPL** [comment]
Jasne, dodam info do readme i dodam linka do repo w stronie

**Comment by ChrisRPL** [comment]
@kasztan2 Dodałem zmiany do repo i apki w 04d1bb9ce8d1bcafa0176c6a1ed979bcdf3db381 oraz b2f1d4c1eaceb0692d6b019a3f9a0aa857c40ed0, zamykam issue
